### ISSUE TITLE
Pub get error

### ISSUE THREAD

**Issue by Harishwarrior** [Afonsocraposo/ppg#8] opened 2020-11-15 09:21 UTC
stderr: remote: Repository not found.
fatal: repository 'https://github.com/Renesanse/plugins.git/' not found

It seems like the repo you used for camera functionality got removed or deleted. I can't access it. For you ,it works. because, it's cached on your system.

Thanks for sharing this repo on Github and I saw your medium article , it's awesome.

Anyway feel free to close this issue.

**Comment by afonsocraposo** [comment] 2020-11-15 11:19
Hello, this is a duplicate of https://github.com/Afonsocraposo/ppg/issues/6
Thank you for your feedback and I'm glad you enjoyed it.
You can also use the plugin I'm developing to do this:
https://pub.dev/packages/manual_camera/

**Closed as completed by afonsocraposo** 2020-11-15 11:19 UTC
